version: '3.8'
services:
  node-server:
    build: ./node-server
    container_name: node-server
    ports:
      - '8080:8080'
    volumes:
      - ./node-server:/app
      - /app/node_modules
  reactapp:
    build: ./react-app
    container_name: react-app
    ports:
      - '3000:5173'
    stdin_open: true
    tty: true
 